"""Git operations, diff, and worktree management.

This module re-exports symbols from :mod:`loop_kit._core` that belong to the
``git_helpers`` section of the ``_SECTION_OWNERSHIP_MAP``.
"""

from loop_kit._core import *  # noqa: F401,F403
from loop_kit._core import _build_lane_worker_prompt, _cherry_pick_lane_reports, _cleanup_lane_worktrees_for_round, _commit_touched_paths, _create_lane_worktree, _current_sha, _diff, _dirty_tracked_paths, _git, _git_at, _git_worktree_paths, _initialize_lane_state, _integration_lane_state_entry, _is_git_repo_root, _is_valid_ref, _lane_backend_for_dispatch, _lane_dependency_blockers, _lane_dispatch_role_name, _lane_local_loop_dir, _lane_local_work_report_path, _lane_merge_conflict_policy, _lane_preflight_conflict_summary, _lane_preserve_worktrees_on_failure, _lane_report_path, _lane_reports_dir, _lane_review_report_path, _lane_review_reports_dir, _lane_review_request_path, _lane_review_requests_dir, _lane_review_verdict_from_report, _lane_source_commit_chain, _lane_task_component, _lane_worktree_branch_name, _lane_worktrees_round_dir, _lane_worktrees_task_dir, _log_oneline, _merge_lane_work_reports, _parse_porcelain_path, _preflight_lane_merge_conflicts, _prepare_lane_loop_inputs, _prepare_lane_worktrees, _reset_bus, _resolve_commit_oid, _restore_merge_head_after_failure, _run_integration_acceptance_checks, _safe_git_component, _save_lane_state_snapshot, _task_lane_ids, _truncate_diff  # noqa: F401

__all__ = ['_build_lane_worker_prompt', '_cherry_pick_lane_reports', '_cleanup_lane_worktrees_for_round', '_commit_touched_paths', '_create_lane_worktree', '_current_sha', '_diff', '_dirty_tracked_paths', '_git', '_git_at', '_git_worktree_paths', '_initialize_lane_state', '_integration_lane_state_entry', '_is_git_repo_root', '_is_valid_ref', '_lane_backend_for_dispatch', '_lane_dependency_blockers', '_lane_dispatch_role_name', '_lane_local_loop_dir', '_lane_local_work_report_path', '_lane_merge_conflict_policy', '_lane_preflight_conflict_summary', '_lane_preserve_worktrees_on_failure', '_lane_report_path', '_lane_reports_dir', '_lane_review_report_path', '_lane_review_reports_dir', '_lane_review_request_path', '_lane_review_requests_dir', '_lane_review_verdict_from_report', '_lane_source_commit_chain', '_lane_task_component', '_lane_worktree_branch_name', '_lane_worktrees_round_dir', '_lane_worktrees_task_dir', '_log_oneline', '_merge_lane_work_reports', '_parse_porcelain_path', '_preflight_lane_merge_conflicts', '_prepare_lane_loop_inputs', '_prepare_lane_worktrees', '_reset_bus', '_resolve_commit_oid', '_restore_merge_head_after_failure', '_run_integration_acceptance_checks', '_safe_git_component', '_save_lane_state_snapshot', '_task_lane_ids', '_truncate_diff']
