"""Knowledge retrieval, FTS, and patterns.

This module re-exports symbols from :mod:`loop_kit._core` that belong to the
``knowledge`` section of the ``_SECTION_OWNERSHIP_MAP``.
"""

from loop_kit._core import *  # noqa: F401,F403
from loop_kit._core import _as_prompt_list, _atomic_write_jsonl, _atomic_write_text, _build_knowledge_fts_query, _build_knowledge_like_params, _build_task_packet, _coerce_confidence, _coerce_non_negative_int, _coerce_non_negative_ms, _collect_default_knowledge_rows, _collect_dispatch_phase_metrics_events, _connect_knowledge_db, _dedupe_pattern_entries, _dedupe_text_knowledge_entries, _dispatch_subphase_metrics_from_telemetry, _enrich_work_report_runtime_fields, _ensure_knowledge_fts_table, _ensure_knowledge_index_schema, _escape_sql_like, _estimate_backend_cost_cents, _fallback_ranked_knowledge, _format_metric_ms, _format_pattern_prompt_line, _function_index, _function_index_cache, _get_knowledge_fts_cache, _handoff_round_from_filename, _is_path_under_root, _is_safe_scope_pattern, _iter_fix_list_query_fragments, _iter_prior_round_feedback_fragments, _iter_task_card_query_fragments, _knowledge_db_cache_key, _knowledge_default_specs, _knowledge_index_rows, _knowledge_meta_get, _knowledge_meta_set, _knowledge_query_fragments, _knowledge_query_tokens, _knowledge_rows_version, _knowledge_score, _knowledge_table_exists, _knowledge_tokens, _latest_handoff_entry, _load_markdown_knowledge_entries, _load_patterns_with_governance, _load_pitfalls, _load_project_facts, _nearest_rank_percentile, _normalize_lane_runtime_metrics, _normalize_pattern_entry, _normalize_token_usage, _normalized_backend_name, _parse_confidence_arg, _parse_non_negative_int_arg, _parse_positive_int_arg, _parse_utc_iso8601, _parse_utc_iso8601_sort_key, _path_tokens, _prune_jsonl_by_source_version, _query_knowledge_sqlite, _read_jsonl_entries, _read_markdown_knowledge_lines, _read_text_optional, _render_handoff_context_section, _render_knowledge_section, _render_quickstart_context_section, _render_table, _render_task_card_section, _retrieve_ranked_knowledge, _runtime_cost_and_token_fields, _select_ranked_patterns, _select_ranked_text_knowledge, _set_knowledge_fts_cache, _source_version_from_file, _string_list, _strip_list_prefix, _summarize_dispatch_phase_metrics, _summarize_dispatch_subphase_metrics, _summarize_named_dispatch_metrics, _sync_knowledge_sqlite_index, _to_utc_iso8601, _write_patterns_jsonl, cmd_knowledge_add, cmd_knowledge_benchmark, cmd_knowledge_dedupe, cmd_knowledge_list, cmd_knowledge_prune  # noqa: F401

__all__ = ['_as_prompt_list', '_atomic_write_jsonl', '_atomic_write_text', '_build_knowledge_fts_query', '_build_knowledge_like_params', '_build_task_packet', '_coerce_confidence', '_coerce_non_negative_int', '_coerce_non_negative_ms', '_collect_default_knowledge_rows', '_collect_dispatch_phase_metrics_events', '_connect_knowledge_db', '_dedupe_pattern_entries', '_dedupe_text_knowledge_entries', '_dispatch_subphase_metrics_from_telemetry', '_enrich_work_report_runtime_fields', '_ensure_knowledge_fts_table', '_ensure_knowledge_index_schema', '_escape_sql_like', '_estimate_backend_cost_cents', '_fallback_ranked_knowledge', '_format_metric_ms', '_format_pattern_prompt_line', '_function_index', '_function_index_cache', '_get_knowledge_fts_cache', '_handoff_round_from_filename', '_is_path_under_root', '_is_safe_scope_pattern', '_iter_fix_list_query_fragments', '_iter_prior_round_feedback_fragments', '_iter_task_card_query_fragments', '_knowledge_db_cache_key', '_knowledge_default_specs', '_knowledge_index_rows', '_knowledge_meta_get', '_knowledge_meta_set', '_knowledge_query_fragments', '_knowledge_query_tokens', '_knowledge_rows_version', '_knowledge_score', '_knowledge_table_exists', '_knowledge_tokens', '_latest_handoff_entry', '_load_markdown_knowledge_entries', '_load_patterns_with_governance', '_load_pitfalls', '_load_project_facts', '_nearest_rank_percentile', '_normalize_lane_runtime_metrics', '_normalize_pattern_entry', '_normalize_token_usage', '_normalized_backend_name', '_parse_confidence_arg', '_parse_non_negative_int_arg', '_parse_positive_int_arg', '_parse_utc_iso8601', '_parse_utc_iso8601_sort_key', '_path_tokens', '_prune_jsonl_by_source_version', '_query_knowledge_sqlite', '_read_jsonl_entries', '_read_markdown_knowledge_lines', '_read_text_optional', '_render_handoff_context_section', '_render_knowledge_section', '_render_quickstart_context_section', '_render_table', '_render_task_card_section', '_retrieve_ranked_knowledge', '_runtime_cost_and_token_fields', '_select_ranked_patterns', '_select_ranked_text_knowledge', '_set_knowledge_fts_cache', '_source_version_from_file', '_string_list', '_strip_list_prefix', '_summarize_dispatch_phase_metrics', '_summarize_dispatch_subphase_metrics', '_summarize_named_dispatch_metrics', '_sync_knowledge_sqlite_index', '_to_utc_iso8601', '_write_patterns_jsonl', 'cmd_knowledge_add', 'cmd_knowledge_benchmark', 'cmd_knowledge_dedupe', 'cmd_knowledge_list', 'cmd_knowledge_prune']
